/*
 * Generated by gdbus-codegen 2.54.3. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "watcher_generated.h"

#include <string.h>
#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  gboolean use_gvariant;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        {
          /* Avoid -Wfloat-equal warnings by doing a direct bit compare */
          gdouble da = g_value_get_double (a);
          gdouble db = g_value_get_double (b);
          ret = memcmp (&da, &db, sizeof (gdouble)) == 0;
        }
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface org.kde.StatusNotifierWatcher
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:SniWatcher
 * @title: SniWatcher
 * @short_description: Generated C code for the org.kde.StatusNotifierWatcher D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-org-kde-StatusNotifierWatcher.top_of_page">org.kde.StatusNotifierWatcher</link> D-Bus interface in C.
 */

/* ---- Introspection data for org.kde.StatusNotifierWatcher ---- */

static const _ExtendedGDBusArgInfo _sni_watcher__method_info_register_status_notifier_item_IN_ARG_service =
{
  {
    -1,
    (gchar *) "service",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _sni_watcher__method_info_register_status_notifier_item_IN_ARG_pointers[] =
{
  &_sni_watcher__method_info_register_status_notifier_item_IN_ARG_service,
  NULL
};

static const _ExtendedGDBusMethodInfo _sni_watcher__method_info_register_status_notifier_item =
{
  {
    -1,
    (gchar *) "RegisterStatusNotifierItem",
    (GDBusArgInfo **) &_sni_watcher__method_info_register_status_notifier_item_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-register-status-notifier-item",
  FALSE
};

static const _ExtendedGDBusArgInfo _sni_watcher__method_info_register_status_notifier_host_IN_ARG_service =
{
  {
    -1,
    (gchar *) "service",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _sni_watcher__method_info_register_status_notifier_host_IN_ARG_pointers[] =
{
  &_sni_watcher__method_info_register_status_notifier_host_IN_ARG_service,
  NULL
};

static const _ExtendedGDBusMethodInfo _sni_watcher__method_info_register_status_notifier_host =
{
  {
    -1,
    (gchar *) "RegisterStatusNotifierHost",
    (GDBusArgInfo **) &_sni_watcher__method_info_register_status_notifier_host_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-register-status-notifier-host",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _sni_watcher__method_info_pointers[] =
{
  &_sni_watcher__method_info_register_status_notifier_item,
  &_sni_watcher__method_info_register_status_notifier_host,
  NULL
};

static const _ExtendedGDBusArgInfo _sni_watcher__signal_info_status_notifier_item_registered_ARG_unnamed_arg0 =
{
  {
    -1,
    (gchar *) "unnamed_arg0",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _sni_watcher__signal_info_status_notifier_item_registered_ARG_pointers[] =
{
  &_sni_watcher__signal_info_status_notifier_item_registered_ARG_unnamed_arg0,
  NULL
};

static const _ExtendedGDBusSignalInfo _sni_watcher__signal_info_status_notifier_item_registered =
{
  {
    -1,
    (gchar *) "StatusNotifierItemRegistered",
    (GDBusArgInfo **) &_sni_watcher__signal_info_status_notifier_item_registered_ARG_pointers,
    NULL
  },
  "status-notifier-item-registered"
};

static const _ExtendedGDBusArgInfo _sni_watcher__signal_info_status_notifier_item_unregistered_ARG_unnamed_arg0 =
{
  {
    -1,
    (gchar *) "unnamed_arg0",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _sni_watcher__signal_info_status_notifier_item_unregistered_ARG_pointers[] =
{
  &_sni_watcher__signal_info_status_notifier_item_unregistered_ARG_unnamed_arg0,
  NULL
};

static const _ExtendedGDBusSignalInfo _sni_watcher__signal_info_status_notifier_item_unregistered =
{
  {
    -1,
    (gchar *) "StatusNotifierItemUnregistered",
    (GDBusArgInfo **) &_sni_watcher__signal_info_status_notifier_item_unregistered_ARG_pointers,
    NULL
  },
  "status-notifier-item-unregistered"
};

static const _ExtendedGDBusSignalInfo _sni_watcher__signal_info_status_notifier_host_registered =
{
  {
    -1,
    (gchar *) "StatusNotifierHostRegistered",
    NULL,
    NULL
  },
  "status-notifier-host-registered"
};

static const _ExtendedGDBusSignalInfo _sni_watcher__signal_info_status_notifier_host_unregistered =
{
  {
    -1,
    (gchar *) "StatusNotifierHostUnregistered",
    NULL,
    NULL
  },
  "status-notifier-host-unregistered"
};

static const _ExtendedGDBusSignalInfo * const _sni_watcher__signal_info_pointers[] =
{
  &_sni_watcher__signal_info_status_notifier_item_registered,
  &_sni_watcher__signal_info_status_notifier_item_unregistered,
  &_sni_watcher__signal_info_status_notifier_host_registered,
  &_sni_watcher__signal_info_status_notifier_host_unregistered,
  NULL
};

static const GDBusAnnotationInfo _sni_watcher__property_registered_status_notifier_items_annotation_info_0 =
{
  -1,
  (gchar *) "org.qtproject.QtDBus.QtTypeName.Out0",
  (gchar *) "QStringList",
  NULL
};

static const GDBusAnnotationInfo * const _sni_watcher__property_registered_status_notifier_items_annotation_info_pointers[] =
{
  &_sni_watcher__property_registered_status_notifier_items_annotation_info_0,
  NULL
};

static const _ExtendedGDBusPropertyInfo _sni_watcher__property_info_registered_status_notifier_items =
{
  {
    -1,
    (gchar *) "RegisteredStatusNotifierItems",
    (gchar *) "as",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    (GDBusAnnotationInfo **) &_sni_watcher__property_registered_status_notifier_items_annotation_info_pointers
  },
  "registered-status-notifier-items",
  FALSE
};

static const _ExtendedGDBusPropertyInfo _sni_watcher__property_info_is_status_notifier_host_registered =
{
  {
    -1,
    (gchar *) "IsStatusNotifierHostRegistered",
    (gchar *) "b",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "is-status-notifier-host-registered",
  FALSE
};

static const _ExtendedGDBusPropertyInfo _sni_watcher__property_info_protocol_version =
{
  {
    -1,
    (gchar *) "ProtocolVersion",
    (gchar *) "i",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "protocol-version",
  FALSE
};

static const _ExtendedGDBusPropertyInfo * const _sni_watcher__property_info_pointers[] =
{
  &_sni_watcher__property_info_registered_status_notifier_items,
  &_sni_watcher__property_info_is_status_notifier_host_registered,
  &_sni_watcher__property_info_protocol_version,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _sni_watcher__interface_info =
{
  {
    -1,
    (gchar *) "org.kde.StatusNotifierWatcher",
    (GDBusMethodInfo **) &_sni_watcher__method_info_pointers,
    (GDBusSignalInfo **) &_sni_watcher__signal_info_pointers,
    (GDBusPropertyInfo **) &_sni_watcher__property_info_pointers,
    NULL
  },
  "",
};


/**
 * sni_watcher__interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-org-kde-StatusNotifierWatcher.top_of_page">org.kde.StatusNotifierWatcher</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
sni_watcher__interface_info (void)
{
  return (GDBusInterfaceInfo *) &_sni_watcher__interface_info.parent_struct;
}

/**
 * sni_watcher__override_properties:
 * @klass: The class structure for a #GObject<!-- -->-derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #SniWatcher interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
sni_watcher__override_properties (GObjectClass *klass, guint property_id_begin)
{
  g_object_class_override_property (klass, property_id_begin++, "registered-status-notifier-items");
  g_object_class_override_property (klass, property_id_begin++, "is-status-notifier-host-registered");
  g_object_class_override_property (klass, property_id_begin++, "protocol-version");
  return property_id_begin - 1;
}



/**
 * SniWatcher:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-org-kde-StatusNotifierWatcher.top_of_page">org.kde.StatusNotifierWatcher</link>.
 */

/**
 * SniWatcherIface:
 * @parent_iface: The parent interface.
 * @handle_register_status_notifier_host: Handler for the #SniWatcher::handle-register-status-notifier-host signal.
 * @handle_register_status_notifier_item: Handler for the #SniWatcher::handle-register-status-notifier-item signal.
 * @get_is_status_notifier_host_registered: Getter for the #SniWatcher:is-status-notifier-host-registered property.
 * @get_protocol_version: Getter for the #SniWatcher:protocol-version property.
 * @get_registered_status_notifier_items: Getter for the #SniWatcher:registered-status-notifier-items property.
 * @status_notifier_host_registered: Handler for the #SniWatcher::status-notifier-host-registered signal.
 * @status_notifier_host_unregistered: Handler for the #SniWatcher::status-notifier-host-unregistered signal.
 * @status_notifier_item_registered: Handler for the #SniWatcher::status-notifier-item-registered signal.
 * @status_notifier_item_unregistered: Handler for the #SniWatcher::status-notifier-item-unregistered signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-org-kde-StatusNotifierWatcher.top_of_page">org.kde.StatusNotifierWatcher</link>.
 */

typedef SniWatcherIface SniWatcherInterface;
G_DEFINE_INTERFACE (SniWatcher, sni_watcher_, G_TYPE_OBJECT)

static void
sni_watcher__default_init (SniWatcherIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * SniWatcher::handle-register-status-notifier-item:
   * @object: A #SniWatcher.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_service: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-kde-StatusNotifierWatcher.RegisterStatusNotifierItem">RegisterStatusNotifierItem()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call sni_watcher__complete_register_status_notifier_item() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-register-status-notifier-item",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (SniWatcherIface, handle_register_status_notifier_item),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

  /**
   * SniWatcher::handle-register-status-notifier-host:
   * @object: A #SniWatcher.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_service: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-kde-StatusNotifierWatcher.RegisterStatusNotifierHost">RegisterStatusNotifierHost()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call sni_watcher__complete_register_status_notifier_host() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-register-status-notifier-host",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (SniWatcherIface, handle_register_status_notifier_host),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

  /* GObject signals for received D-Bus signals: */
  /**
   * SniWatcher::status-notifier-item-registered:
   * @object: A #SniWatcher.
   * @arg_unnamed_arg0: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-org-kde-StatusNotifierWatcher.StatusNotifierItemRegistered">"StatusNotifierItemRegistered"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("status-notifier-item-registered",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (SniWatcherIface, status_notifier_item_registered),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    1, G_TYPE_STRING);

  /**
   * SniWatcher::status-notifier-item-unregistered:
   * @object: A #SniWatcher.
   * @arg_unnamed_arg0: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-org-kde-StatusNotifierWatcher.StatusNotifierItemUnregistered">"StatusNotifierItemUnregistered"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("status-notifier-item-unregistered",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (SniWatcherIface, status_notifier_item_unregistered),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    1, G_TYPE_STRING);

  /**
   * SniWatcher::status-notifier-host-registered:
   * @object: A #SniWatcher.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-org-kde-StatusNotifierWatcher.StatusNotifierHostRegistered">"StatusNotifierHostRegistered"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("status-notifier-host-registered",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (SniWatcherIface, status_notifier_host_registered),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    0);

  /**
   * SniWatcher::status-notifier-host-unregistered:
   * @object: A #SniWatcher.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-org-kde-StatusNotifierWatcher.StatusNotifierHostUnregistered">"StatusNotifierHostUnregistered"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("status-notifier-host-unregistered",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (SniWatcherIface, status_notifier_host_unregistered),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    0);

  /* GObject properties for D-Bus properties: */
  /**
   * SniWatcher:registered-status-notifier-items:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-kde-StatusNotifierWatcher.RegisteredStatusNotifierItems">"RegisteredStatusNotifierItems"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_boxed ("registered-status-notifier-items", "RegisteredStatusNotifierItems", "RegisteredStatusNotifierItems", G_TYPE_STRV, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * SniWatcher:is-status-notifier-host-registered:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-kde-StatusNotifierWatcher.IsStatusNotifierHostRegistered">"IsStatusNotifierHostRegistered"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_boolean ("is-status-notifier-host-registered", "IsStatusNotifierHostRegistered", "IsStatusNotifierHostRegistered", FALSE, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * SniWatcher:protocol-version:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-kde-StatusNotifierWatcher.ProtocolVersion">"ProtocolVersion"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_int ("protocol-version", "ProtocolVersion", "ProtocolVersion", G_MININT32, G_MAXINT32, 0, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
}

/**
 * sni_watcher__get_registered_status_notifier_items: (skip)
 * @object: A #SniWatcher.
 *
 * Gets the value of the <link linkend="gdbus-property-org-kde-StatusNotifierWatcher.RegisteredStatusNotifierItems">"RegisteredStatusNotifierItems"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * <warning>The returned value is only valid until the property changes so on the client-side it is only safe to use this function on the thread where @object was constructed. Use sni_watcher__dup_registered_status_notifier_items() if on another thread.</warning>
 *
 * Returns: (transfer none): The property value or %NULL if the property is not set. Do not free the returned value, it belongs to @object.
 */
const gchar *const *
sni_watcher__get_registered_status_notifier_items (SniWatcher *object)
{
  return SNI_WATCHER__GET_IFACE (object)->get_registered_status_notifier_items (object);
}

/**
 * sni_watcher__dup_registered_status_notifier_items: (skip)
 * @object: A #SniWatcher.
 *
 * Gets a copy of the <link linkend="gdbus-property-org-kde-StatusNotifierWatcher.RegisteredStatusNotifierItems">"RegisteredStatusNotifierItems"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: (transfer full): The property value or %NULL if the property is not set. The returned value should be freed with g_strfreev().
 */
gchar **
sni_watcher__dup_registered_status_notifier_items (SniWatcher *object)
{
  gchar **value;
  g_object_get (G_OBJECT (object), "registered-status-notifier-items", &value, NULL);
  return value;
}

/**
 * sni_watcher__set_registered_status_notifier_items: (skip)
 * @object: A #SniWatcher.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-kde-StatusNotifierWatcher.RegisteredStatusNotifierItems">"RegisteredStatusNotifierItems"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
sni_watcher__set_registered_status_notifier_items (SniWatcher *object, const gchar *const *value)
{
  g_object_set (G_OBJECT (object), "registered-status-notifier-items", value, NULL);
}

/**
 * sni_watcher__get_is_status_notifier_host_registered: (skip)
 * @object: A #SniWatcher.
 *
 * Gets the value of the <link linkend="gdbus-property-org-kde-StatusNotifierWatcher.IsStatusNotifierHostRegistered">"IsStatusNotifierHostRegistered"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: The property value.
 */
gboolean 
sni_watcher__get_is_status_notifier_host_registered (SniWatcher *object)
{
  return SNI_WATCHER__GET_IFACE (object)->get_is_status_notifier_host_registered (object);
}

/**
 * sni_watcher__set_is_status_notifier_host_registered: (skip)
 * @object: A #SniWatcher.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-kde-StatusNotifierWatcher.IsStatusNotifierHostRegistered">"IsStatusNotifierHostRegistered"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
sni_watcher__set_is_status_notifier_host_registered (SniWatcher *object, gboolean value)
{
  g_object_set (G_OBJECT (object), "is-status-notifier-host-registered", value, NULL);
}

/**
 * sni_watcher__get_protocol_version: (skip)
 * @object: A #SniWatcher.
 *
 * Gets the value of the <link linkend="gdbus-property-org-kde-StatusNotifierWatcher.ProtocolVersion">"ProtocolVersion"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: The property value.
 */
gint 
sni_watcher__get_protocol_version (SniWatcher *object)
{
  return SNI_WATCHER__GET_IFACE (object)->get_protocol_version (object);
}

/**
 * sni_watcher__set_protocol_version: (skip)
 * @object: A #SniWatcher.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-kde-StatusNotifierWatcher.ProtocolVersion">"ProtocolVersion"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
sni_watcher__set_protocol_version (SniWatcher *object, gint value)
{
  g_object_set (G_OBJECT (object), "protocol-version", value, NULL);
}

/**
 * sni_watcher__emit_status_notifier_item_registered:
 * @object: A #SniWatcher.
 * @arg_unnamed_arg0: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-org-kde-StatusNotifierWatcher.StatusNotifierItemRegistered">"StatusNotifierItemRegistered"</link> D-Bus signal.
 */
void
sni_watcher__emit_status_notifier_item_registered (
    SniWatcher *object,
    const gchar *arg_unnamed_arg0)
{
  g_signal_emit_by_name (object, "status-notifier-item-registered", arg_unnamed_arg0);
}

/**
 * sni_watcher__emit_status_notifier_item_unregistered:
 * @object: A #SniWatcher.
 * @arg_unnamed_arg0: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-org-kde-StatusNotifierWatcher.StatusNotifierItemUnregistered">"StatusNotifierItemUnregistered"</link> D-Bus signal.
 */
void
sni_watcher__emit_status_notifier_item_unregistered (
    SniWatcher *object,
    const gchar *arg_unnamed_arg0)
{
  g_signal_emit_by_name (object, "status-notifier-item-unregistered", arg_unnamed_arg0);
}

/**
 * sni_watcher__emit_status_notifier_host_registered:
 * @object: A #SniWatcher.
 *
 * Emits the <link linkend="gdbus-signal-org-kde-StatusNotifierWatcher.StatusNotifierHostRegistered">"StatusNotifierHostRegistered"</link> D-Bus signal.
 */
void
sni_watcher__emit_status_notifier_host_registered (
    SniWatcher *object)
{
  g_signal_emit_by_name (object, "status-notifier-host-registered");
}

/**
 * sni_watcher__emit_status_notifier_host_unregistered:
 * @object: A #SniWatcher.
 *
 * Emits the <link linkend="gdbus-signal-org-kde-StatusNotifierWatcher.StatusNotifierHostUnregistered">"StatusNotifierHostUnregistered"</link> D-Bus signal.
 */
void
sni_watcher__emit_status_notifier_host_unregistered (
    SniWatcher *object)
{
  g_signal_emit_by_name (object, "status-notifier-host-unregistered");
}

/**
 * sni_watcher__call_register_status_notifier_item:
 * @proxy: A #SniWatcherProxy.
 * @arg_service: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-kde-StatusNotifierWatcher.RegisterStatusNotifierItem">RegisterStatusNotifierItem()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call sni_watcher__call_register_status_notifier_item_finish() to get the result of the operation.
 *
 * See sni_watcher__call_register_status_notifier_item_sync() for the synchronous, blocking version of this method.
 */
void
sni_watcher__call_register_status_notifier_item (
    SniWatcher *proxy,
    const gchar *arg_service,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "RegisterStatusNotifierItem",
    g_variant_new ("(s)",
                   arg_service),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * sni_watcher__call_register_status_notifier_item_finish:
 * @proxy: A #SniWatcherProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to sni_watcher__call_register_status_notifier_item().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with sni_watcher__call_register_status_notifier_item().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
sni_watcher__call_register_status_notifier_item_finish (
    SniWatcher *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * sni_watcher__call_register_status_notifier_item_sync:
 * @proxy: A #SniWatcherProxy.
 * @arg_service: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-kde-StatusNotifierWatcher.RegisterStatusNotifierItem">RegisterStatusNotifierItem()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See sni_watcher__call_register_status_notifier_item() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
sni_watcher__call_register_status_notifier_item_sync (
    SniWatcher *proxy,
    const gchar *arg_service,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "RegisterStatusNotifierItem",
    g_variant_new ("(s)",
                   arg_service),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * sni_watcher__call_register_status_notifier_host:
 * @proxy: A #SniWatcherProxy.
 * @arg_service: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-kde-StatusNotifierWatcher.RegisterStatusNotifierHost">RegisterStatusNotifierHost()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call sni_watcher__call_register_status_notifier_host_finish() to get the result of the operation.
 *
 * See sni_watcher__call_register_status_notifier_host_sync() for the synchronous, blocking version of this method.
 */
void
sni_watcher__call_register_status_notifier_host (
    SniWatcher *proxy,
    const gchar *arg_service,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "RegisterStatusNotifierHost",
    g_variant_new ("(s)",
                   arg_service),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * sni_watcher__call_register_status_notifier_host_finish:
 * @proxy: A #SniWatcherProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to sni_watcher__call_register_status_notifier_host().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with sni_watcher__call_register_status_notifier_host().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
sni_watcher__call_register_status_notifier_host_finish (
    SniWatcher *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * sni_watcher__call_register_status_notifier_host_sync:
 * @proxy: A #SniWatcherProxy.
 * @arg_service: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-kde-StatusNotifierWatcher.RegisterStatusNotifierHost">RegisterStatusNotifierHost()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See sni_watcher__call_register_status_notifier_host() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
sni_watcher__call_register_status_notifier_host_sync (
    SniWatcher *proxy,
    const gchar *arg_service,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "RegisterStatusNotifierHost",
    g_variant_new ("(s)",
                   arg_service),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * sni_watcher__complete_register_status_notifier_item:
 * @object: A #SniWatcher.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-kde-StatusNotifierWatcher.RegisterStatusNotifierItem">RegisterStatusNotifierItem()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
sni_watcher__complete_register_status_notifier_item (
    SniWatcher *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * sni_watcher__complete_register_status_notifier_host:
 * @object: A #SniWatcher.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-kde-StatusNotifierWatcher.RegisterStatusNotifierHost">RegisterStatusNotifierHost()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
sni_watcher__complete_register_status_notifier_host (
    SniWatcher *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/* ------------------------------------------------------------------------ */

/**
 * SniWatcherProxy:
 *
 * The #SniWatcherProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * SniWatcherProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #SniWatcherProxy.
 */

struct _SniWatcherProxyPrivate
{
  GData *qdata;
};

static void sni_watcher__proxy_iface_init (SniWatcherIface *iface);

#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (SniWatcherProxy, sni_watcher__proxy, G_TYPE_DBUS_PROXY,
                         G_ADD_PRIVATE (SniWatcherProxy)
                         G_IMPLEMENT_INTERFACE (SNI_WATCHER_TYPE_, sni_watcher__proxy_iface_init))

#else
G_DEFINE_TYPE_WITH_CODE (SniWatcherProxy, sni_watcher__proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (SNI_WATCHER_TYPE_, sni_watcher__proxy_iface_init))

#endif
static void
sni_watcher__proxy_finalize (GObject *object)
{
  SniWatcherProxy *proxy = SNI_WATCHER__PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (sni_watcher__proxy_parent_class)->finalize (object);
}

static void
sni_watcher__proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
  const _ExtendedGDBusPropertyInfo *info;
  GVariant *variant;
  g_assert (prop_id != 0 && prop_id - 1 < 3);
  info = _sni_watcher__property_info_pointers[prop_id - 1];
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (object), info->parent_struct.name);
  if (info->use_gvariant)
    {
      g_value_set_variant (value, variant);
    }
  else
    {
      if (variant != NULL)
        g_dbus_gvariant_to_gvalue (variant, value);
    }
  if (variant != NULL)
    g_variant_unref (variant);
}

static void
sni_watcher__proxy_set_property_cb (GDBusProxy *proxy,
  GAsyncResult *res,
  gpointer      user_data)
{
  const _ExtendedGDBusPropertyInfo *info = user_data;
  GError *error;
  GVariant *_ret;
  error = NULL;
  _ret = g_dbus_proxy_call_finish (proxy, res, &error);
  if (!_ret)
    {
      g_warning ("Error setting property '%s' on interface org.kde.StatusNotifierWatcher: %s (%s, %d)",
                 info->parent_struct.name, 
                 error->message, g_quark_to_string (error->domain), error->code);
      g_error_free (error);
    }
  else
    {
      g_variant_unref (_ret);
    }
}

static void
sni_watcher__proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
  const _ExtendedGDBusPropertyInfo *info;
  GVariant *variant;
  g_assert (prop_id != 0 && prop_id - 1 < 3);
  info = _sni_watcher__property_info_pointers[prop_id - 1];
  variant = g_dbus_gvalue_to_gvariant (value, G_VARIANT_TYPE (info->parent_struct.signature));
  g_dbus_proxy_call (G_DBUS_PROXY (object),
    "org.freedesktop.DBus.Properties.Set",
    g_variant_new ("(ssv)", "org.kde.StatusNotifierWatcher", info->parent_struct.name, variant),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    NULL, (GAsyncReadyCallback) sni_watcher__proxy_set_property_cb, (GDBusPropertyInfo *) &info->parent_struct);
  g_variant_unref (variant);
}

static void
sni_watcher__proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name G_GNUC_UNUSED,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  gsize num_params;
  gsize n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_sni_watcher__interface_info.parent_struct, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], SNI_WATCHER_TYPE_);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, SNI_WATCHER_TYPE_);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
sni_watcher__proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  SniWatcherProxy *proxy = SNI_WATCHER__PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_sni_watcher__interface_info.parent_struct, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_sni_watcher__interface_info.parent_struct, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static const gchar *const *
sni_watcher__proxy_get_registered_status_notifier_items (SniWatcher *object)
{
  SniWatcherProxy *proxy = SNI_WATCHER__PROXY (object);
  GVariant *variant;
  const gchar *const *value = NULL;
  value = g_datalist_get_data (&proxy->priv->qdata, "RegisteredStatusNotifierItems");
  if (value != NULL)
    return value;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "RegisteredStatusNotifierItems");
  if (variant != NULL)
    {
      value = g_variant_get_strv (variant, NULL);
      g_datalist_set_data_full (&proxy->priv->qdata, "RegisteredStatusNotifierItems", (gpointer) value, g_free);
      g_variant_unref (variant);
    }
  return value;
}

static gboolean 
sni_watcher__proxy_get_is_status_notifier_host_registered (SniWatcher *object)
{
  SniWatcherProxy *proxy = SNI_WATCHER__PROXY (object);
  GVariant *variant;
  gboolean value = 0;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "IsStatusNotifierHostRegistered");
  if (variant != NULL)
    {
      value = g_variant_get_boolean (variant);
      g_variant_unref (variant);
    }
  return value;
}

static gint 
sni_watcher__proxy_get_protocol_version (SniWatcher *object)
{
  SniWatcherProxy *proxy = SNI_WATCHER__PROXY (object);
  GVariant *variant;
  gint value = 0;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "ProtocolVersion");
  if (variant != NULL)
    {
      value = g_variant_get_int32 (variant);
      g_variant_unref (variant);
    }
  return value;
}

static void
sni_watcher__proxy_init (SniWatcherProxy *proxy)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  proxy->priv = sni_watcher__proxy_get_instance_private (proxy);
#else
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, SNI_WATCHER_TYPE__PROXY, SniWatcherProxyPrivate);
#endif

  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), sni_watcher__interface_info ());
}

static void
sni_watcher__proxy_class_init (SniWatcherProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = sni_watcher__proxy_finalize;
  gobject_class->get_property = sni_watcher__proxy_get_property;
  gobject_class->set_property = sni_watcher__proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = sni_watcher__proxy_g_signal;
  proxy_class->g_properties_changed = sni_watcher__proxy_g_properties_changed;

  sni_watcher__override_properties (gobject_class, 1);

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (SniWatcherProxyPrivate));
#endif
}

static void
sni_watcher__proxy_iface_init (SniWatcherIface *iface)
{
  iface->get_registered_status_notifier_items = sni_watcher__proxy_get_registered_status_notifier_items;
  iface->get_is_status_notifier_host_registered = sni_watcher__proxy_get_is_status_notifier_host_registered;
  iface->get_protocol_version = sni_watcher__proxy_get_protocol_version;
}

/**
 * sni_watcher__proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-kde-StatusNotifierWatcher.top_of_page">org.kde.StatusNotifierWatcher</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call sni_watcher__proxy_new_finish() to get the result of the operation.
 *
 * See sni_watcher__proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
sni_watcher__proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (SNI_WATCHER_TYPE__PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.kde.StatusNotifierWatcher", NULL);
}

/**
 * sni_watcher__proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to sni_watcher__proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with sni_watcher__proxy_new().
 *
 * Returns: (transfer full) (type SniWatcherProxy): The constructed proxy object or %NULL if @error is set.
 */
SniWatcher *
sni_watcher__proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return SNI_WATCHER_ (ret);
  else
    return NULL;
}

/**
 * sni_watcher__proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-kde-StatusNotifierWatcher.top_of_page">org.kde.StatusNotifierWatcher</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See sni_watcher__proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type SniWatcherProxy): The constructed proxy object or %NULL if @error is set.
 */
SniWatcher *
sni_watcher__proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (SNI_WATCHER_TYPE__PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.kde.StatusNotifierWatcher", NULL);
  if (ret != NULL)
    return SNI_WATCHER_ (ret);
  else
    return NULL;
}


/**
 * sni_watcher__proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like sni_watcher__proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call sni_watcher__proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See sni_watcher__proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
sni_watcher__proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (SNI_WATCHER_TYPE__PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.kde.StatusNotifierWatcher", NULL);
}

/**
 * sni_watcher__proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to sni_watcher__proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with sni_watcher__proxy_new_for_bus().
 *
 * Returns: (transfer full) (type SniWatcherProxy): The constructed proxy object or %NULL if @error is set.
 */
SniWatcher *
sni_watcher__proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return SNI_WATCHER_ (ret);
  else
    return NULL;
}

/**
 * sni_watcher__proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like sni_watcher__proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See sni_watcher__proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type SniWatcherProxy): The constructed proxy object or %NULL if @error is set.
 */
SniWatcher *
sni_watcher__proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (SNI_WATCHER_TYPE__PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.kde.StatusNotifierWatcher", NULL);
  if (ret != NULL)
    return SNI_WATCHER_ (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * SniWatcherSkeleton:
 *
 * The #SniWatcherSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * SniWatcherSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #SniWatcherSkeleton.
 */

struct _SniWatcherSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_sni_watcher__skeleton_handle_method_call (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  SniWatcherSkeleton *skeleton = SNI_WATCHER__SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  gsize num_params;
  guint num_extra;
  gsize n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], SNI_WATCHER_TYPE_);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, SNI_WATCHER_TYPE_);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_sni_watcher__skeleton_handle_get_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  SniWatcherSkeleton *skeleton = SNI_WATCHER__SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_sni_watcher__interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_sni_watcher__skeleton_handle_set_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  SniWatcherSkeleton *skeleton = SNI_WATCHER__SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_sni_watcher__interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _sni_watcher__skeleton_vtable =
{
  _sni_watcher__skeleton_handle_method_call,
  _sni_watcher__skeleton_handle_get_property,
  _sni_watcher__skeleton_handle_set_property,
  {NULL}
};

static GDBusInterfaceInfo *
sni_watcher__skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return sni_watcher__interface_info ();
}

static GDBusInterfaceVTable *
sni_watcher__skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return (GDBusInterfaceVTable *) &_sni_watcher__skeleton_vtable;
}

static GVariant *
sni_watcher__skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  SniWatcherSkeleton *skeleton = SNI_WATCHER__SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_sni_watcher__interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _sni_watcher__interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _sni_watcher__interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _sni_watcher__skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.kde.StatusNotifierWatcher", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static gboolean _sni_watcher__emit_changed (gpointer user_data);

static void
sni_watcher__skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
  SniWatcherSkeleton *skeleton = SNI_WATCHER__SKELETON (_skeleton);
  gboolean emit_changed = FALSE;

  g_mutex_lock (&skeleton->priv->lock);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    {
      g_source_destroy (skeleton->priv->changed_properties_idle_source);
      skeleton->priv->changed_properties_idle_source = NULL;
      emit_changed = TRUE;
    }
  g_mutex_unlock (&skeleton->priv->lock);

  if (emit_changed)
    _sni_watcher__emit_changed (skeleton);
}

static void
_sni_watcher__on_signal_status_notifier_item_registered (
    SniWatcher *object,
    const gchar *arg_unnamed_arg0)
{
  SniWatcherSkeleton *skeleton = SNI_WATCHER__SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("(s)",
                   arg_unnamed_arg0));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.kde.StatusNotifierWatcher", "StatusNotifierItemRegistered",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void
_sni_watcher__on_signal_status_notifier_item_unregistered (
    SniWatcher *object,
    const gchar *arg_unnamed_arg0)
{
  SniWatcherSkeleton *skeleton = SNI_WATCHER__SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("(s)",
                   arg_unnamed_arg0));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.kde.StatusNotifierWatcher", "StatusNotifierItemUnregistered",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void
_sni_watcher__on_signal_status_notifier_host_registered (
    SniWatcher *object)
{
  SniWatcherSkeleton *skeleton = SNI_WATCHER__SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("()"));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.kde.StatusNotifierWatcher", "StatusNotifierHostRegistered",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void
_sni_watcher__on_signal_status_notifier_host_unregistered (
    SniWatcher *object)
{
  SniWatcherSkeleton *skeleton = SNI_WATCHER__SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("()"));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.kde.StatusNotifierWatcher", "StatusNotifierHostUnregistered",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void sni_watcher__skeleton_iface_init (SniWatcherIface *iface);
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (SniWatcherSkeleton, sni_watcher__skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_ADD_PRIVATE (SniWatcherSkeleton)
                         G_IMPLEMENT_INTERFACE (SNI_WATCHER_TYPE_, sni_watcher__skeleton_iface_init))

#else
G_DEFINE_TYPE_WITH_CODE (SniWatcherSkeleton, sni_watcher__skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (SNI_WATCHER_TYPE_, sni_watcher__skeleton_iface_init))

#endif
static void
sni_watcher__skeleton_finalize (GObject *object)
{
  SniWatcherSkeleton *skeleton = SNI_WATCHER__SKELETON (object);
  guint n;
  for (n = 0; n < 3; n++)
    g_value_unset (&skeleton->priv->properties[n]);
  g_free (skeleton->priv->properties);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (sni_watcher__skeleton_parent_class)->finalize (object);
}

static void
sni_watcher__skeleton_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
  SniWatcherSkeleton *skeleton = SNI_WATCHER__SKELETON (object);
  g_assert (prop_id != 0 && prop_id - 1 < 3);
  g_mutex_lock (&skeleton->priv->lock);
  g_value_copy (&skeleton->priv->properties[prop_id - 1], value);
  g_mutex_unlock (&skeleton->priv->lock);
}

static gboolean
_sni_watcher__emit_changed (gpointer user_data)
{
  SniWatcherSkeleton *skeleton = SNI_WATCHER__SKELETON (user_data);
  GList *l;
  GVariantBuilder builder;
  GVariantBuilder invalidated_builder;
  guint num_changes;

  g_mutex_lock (&skeleton->priv->lock);
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  g_variant_builder_init (&invalidated_builder, G_VARIANT_TYPE ("as"));
  for (l = skeleton->priv->changed_properties, num_changes = 0; l != NULL; l = l->next)
    {
      ChangedProperty *cp = l->data;
      GVariant *variant;
      const GValue *cur_value;

      cur_value = &skeleton->priv->properties[cp->prop_id - 1];
      if (!_g_value_equal (cur_value, &cp->orig_value))
        {
          variant = g_dbus_gvalue_to_gvariant (cur_value, G_VARIANT_TYPE (cp->info->parent_struct.signature));
          g_variant_builder_add (&builder, "{sv}", cp->info->parent_struct.name, variant);
          g_variant_unref (variant);
          num_changes++;
        }
    }
  if (num_changes > 0)
    {
      GList *connections, *ll;
      GVariant *signal_variant;
      signal_variant = g_variant_ref_sink (g_variant_new ("(sa{sv}as)", "org.kde.StatusNotifierWatcher",
                                           &builder, &invalidated_builder));
      connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));
      for (ll = connections; ll != NULL; ll = ll->next)
        {
          GDBusConnection *connection = ll->data;

          g_dbus_connection_emit_signal (connection,
                                         NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)),
                                         "org.freedesktop.DBus.Properties",
                                         "PropertiesChanged",
                                         signal_variant,
                                         NULL);
        }
      g_variant_unref (signal_variant);
      g_list_free_full (connections, g_object_unref);
    }
  else
    {
      g_variant_builder_clear (&builder);
      g_variant_builder_clear (&invalidated_builder);
    }
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  skeleton->priv->changed_properties = NULL;
  skeleton->priv->changed_properties_idle_source = NULL;
  g_mutex_unlock (&skeleton->priv->lock);
  return FALSE;
}

static void
_sni_watcher__schedule_emit_changed (SniWatcherSkeleton *skeleton, const _ExtendedGDBusPropertyInfo *info, guint prop_id, const GValue *orig_value)
{
  ChangedProperty *cp;
  GList *l;
  cp = NULL;
  for (l = skeleton->priv->changed_properties; l != NULL; l = l->next)
    {
      ChangedProperty *i_cp = l->data;
      if (i_cp->info == info)
        {
          cp = i_cp;
          break;
        }
    }
  if (cp == NULL)
    {
      cp = g_new0 (ChangedProperty, 1);
      cp->prop_id = prop_id;
      cp->info = info;
      skeleton->priv->changed_properties = g_list_prepend (skeleton->priv->changed_properties, cp);
      g_value_init (&cp->orig_value, G_VALUE_TYPE (orig_value));
      g_value_copy (orig_value, &cp->orig_value);
    }
}

static void
sni_watcher__skeleton_notify (GObject      *object,
  GParamSpec *pspec G_GNUC_UNUSED)
{
  SniWatcherSkeleton *skeleton = SNI_WATCHER__SKELETON (object);
  g_mutex_lock (&skeleton->priv->lock);
  if (skeleton->priv->changed_properties != NULL &&
      skeleton->priv->changed_properties_idle_source == NULL)
    {
      skeleton->priv->changed_properties_idle_source = g_idle_source_new ();
      g_source_set_priority (skeleton->priv->changed_properties_idle_source, G_PRIORITY_DEFAULT);
      g_source_set_callback (skeleton->priv->changed_properties_idle_source, _sni_watcher__emit_changed, g_object_ref (skeleton), (GDestroyNotify) g_object_unref);
      g_source_set_name (skeleton->priv->changed_properties_idle_source, "[generated] _sni_watcher__emit_changed");
      g_source_attach (skeleton->priv->changed_properties_idle_source, skeleton->priv->context);
      g_source_unref (skeleton->priv->changed_properties_idle_source);
    }
  g_mutex_unlock (&skeleton->priv->lock);
}

static void
sni_watcher__skeleton_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
  SniWatcherSkeleton *skeleton = SNI_WATCHER__SKELETON (object);
  g_assert (prop_id != 0 && prop_id - 1 < 3);
  g_mutex_lock (&skeleton->priv->lock);
  g_object_freeze_notify (object);
  if (!_g_value_equal (value, &skeleton->priv->properties[prop_id - 1]))
    {
      if (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)) != NULL)
        _sni_watcher__schedule_emit_changed (skeleton, _sni_watcher__property_info_pointers[prop_id - 1], prop_id, &skeleton->priv->properties[prop_id - 1]);
      g_value_copy (value, &skeleton->priv->properties[prop_id - 1]);
      g_object_notify_by_pspec (object, pspec);
    }
  g_mutex_unlock (&skeleton->priv->lock);
  g_object_thaw_notify (object);
}

static void
sni_watcher__skeleton_init (SniWatcherSkeleton *skeleton)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  skeleton->priv = sni_watcher__skeleton_get_instance_private (skeleton);
#else
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, SNI_WATCHER_TYPE__SKELETON, SniWatcherSkeletonPrivate);
#endif

  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
  skeleton->priv->properties = g_new0 (GValue, 3);
  g_value_init (&skeleton->priv->properties[0], G_TYPE_STRV);
  g_value_init (&skeleton->priv->properties[1], G_TYPE_BOOLEAN);
  g_value_init (&skeleton->priv->properties[2], G_TYPE_INT);
}

static const gchar *const *
sni_watcher__skeleton_get_registered_status_notifier_items (SniWatcher *object)
{
  SniWatcherSkeleton *skeleton = SNI_WATCHER__SKELETON (object);
  const gchar *const *value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_boxed (&(skeleton->priv->properties[0]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static gboolean 
sni_watcher__skeleton_get_is_status_notifier_host_registered (SniWatcher *object)
{
  SniWatcherSkeleton *skeleton = SNI_WATCHER__SKELETON (object);
  gboolean value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_boolean (&(skeleton->priv->properties[1]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static gint 
sni_watcher__skeleton_get_protocol_version (SniWatcher *object)
{
  SniWatcherSkeleton *skeleton = SNI_WATCHER__SKELETON (object);
  gint value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_int (&(skeleton->priv->properties[2]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static void
sni_watcher__skeleton_class_init (SniWatcherSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = sni_watcher__skeleton_finalize;
  gobject_class->get_property = sni_watcher__skeleton_get_property;
  gobject_class->set_property = sni_watcher__skeleton_set_property;
  gobject_class->notify       = sni_watcher__skeleton_notify;


  sni_watcher__override_properties (gobject_class, 1);

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = sni_watcher__skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = sni_watcher__skeleton_dbus_interface_get_properties;
  skeleton_class->flush = sni_watcher__skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = sni_watcher__skeleton_dbus_interface_get_vtable;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (SniWatcherSkeletonPrivate));
#endif
}

static void
sni_watcher__skeleton_iface_init (SniWatcherIface *iface)
{
  iface->status_notifier_item_registered = _sni_watcher__on_signal_status_notifier_item_registered;
  iface->status_notifier_item_unregistered = _sni_watcher__on_signal_status_notifier_item_unregistered;
  iface->status_notifier_host_registered = _sni_watcher__on_signal_status_notifier_host_registered;
  iface->status_notifier_host_unregistered = _sni_watcher__on_signal_status_notifier_host_unregistered;
  iface->get_registered_status_notifier_items = sni_watcher__skeleton_get_registered_status_notifier_items;
  iface->get_is_status_notifier_host_registered = sni_watcher__skeleton_get_is_status_notifier_host_registered;
  iface->get_protocol_version = sni_watcher__skeleton_get_protocol_version;
}

/**
 * sni_watcher__skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-org-kde-StatusNotifierWatcher.top_of_page">org.kde.StatusNotifierWatcher</link>.
 *
 * Returns: (transfer full) (type SniWatcherSkeleton): The skeleton object.
 */
SniWatcher *
sni_watcher__skeleton_new (void)
{
  return SNI_WATCHER_ (g_object_new (SNI_WATCHER_TYPE__SKELETON, NULL));
}

